class PointsSummary < ApplicationRecord
  validates :format, :scoring_area, presence: true, uniqueness: { scope: [:format, :scoring_area], message: "Points are already assigned to this field"}
  validates :points, presence: true
  enum format: {
    T20: 1,
    ODI: 2,
    Test: 3,
  }

  enum scoring_area: {
    run:                       1,
    duck:                      2,
    golden_duck:               3,
    diamond_duck:              4,
    sr_250_or_more:            5,
    sr_200_to_249:             6,
    sr_150_to_199:             7,
    sr_125_to_149:             8,
    sr_100_to_124:             9,
    sr_80_to_99:               10,
    sr_0_to_79:                11,
    wicket:                    12,
    maiden_over:               13,
    rpo_3_or_Less:             14,
    rpo_3_to_4:                15,
    rpo_4_to_5:                16,
    rpo_5_to_6:                17,
    rpo_6_to_7:                18,
    rpo_7_to_9:                19,
    rpo_9_to_10:               20,
    rpo_10_to_12:              21,
    rpo_12_to_14:              22,
    rpo_14_or_more:            23,
    score_30_to_49:            24,
    score_50_to_99:            25,
    score_100_to_149:          26,
    score_150_to_199:          27,
    score_200_to_249:          28,
    score_250_to_299:          29,
    score_300_to_349:          30,
    score_350_or_more:         31,
    not_out_or_retired_hurt:   32,
    three_wickets:             33,
    four_wickets:              34,
    five_wickets:              35,
    six_wickets:               36,
    seven_wickets:             37,
    run_out:                   38,
    stumping:                  39,
    catch_out:                 40,
    wk_catch:                  41,
    wk_dismissals_3:           42,
    wk_dismissals_4_or_more:   43,
    fielding_dismissals_3:     44,
    fielding_dismissals_4plus: 45,
    man_of_the_match:          46,
  }
end
